const ActionTypes = {
  REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  REGISTER_FAIL: 'USER_REGISTER_FAIL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  GET_MENU_SUCCESS: 'GET_MENU_SUCCESS',
  GET_MENU_NONE: 'GET_MENU_NONE'

};

export default ActionTypes;
